{% set name = "phelel" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71c03e57570d023f7bcf20a8c9c76b39c87c2022d18b09af1c31f6e9bb9bbac0

build:
  entry_points:
    - phelel = phelel.scripts.phelel:run
    - phelel-load = phelel.scripts.phelel_load:run
    - velph = phelel.velph.cli:cmd_root
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - phonopy >=2.48.0
    - phono3py >=3.25.0
    - finufft
    - click
    - tomli
    - tomli-w

test:
  imports:
    - phelel
  source_files:
    - test
  commands:
    - pip check
    - phelel --help
    - phelel-load --help
    - velph --help
    - pytest
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://github.com/phonopy/phelel
  description: |
    A code that provides a few computations needed to electron-phonon
    interaction calculation in finite-displacement method.
  summary: Finite-displacement electron-phonon code.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - atztogo
